[default]
    check-filename = false
    unicode = true
    extend-ignore-re = [
        "(?s)^.*?`[^`]+`.*$",
        ".*(#|--|//).*(spellchecker|typos):\\s?ignore[^\\n]*\\n",
        ".*(#|--|//).*(spellchecker|typos):\\s?ignore-next-line[^\\n]*\\n[^\\n]*",
        "[A-Za-z]+://\\S{3,50}:(\\S{8,50})@[\\dA-Za-z#%&+./:=?_~-]+",
    ]

[files]
    extend-exclude = [
        "typos.toml",
        "**/.git*",
        "*.csv",
        "*.js",
        "**/package-lock.json",
        "**/node-modules/**",
        "**/vscodeextension/**",
        "**/.git/objects/**",
        "**/.vscode/**",
        "**/.vscode-insiders/**",
        "**/.tmp-projections/**",
        "**/*.interactive"
    ]
