name: Dependency Review

defaults:
  run:
    # bash --noprofile --norc -e(o) pipefail {0}
    shell: bash

on:
  push:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

env:
  CHECK_PERMISSIONS: 0

permissions: {}

concurrency:
  # pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre_job:
    name: Check for Duplicate Actions
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    permissions:
      actions: write
      contents: read
    outputs:
      should_skip: ${{ steps.check-duplicate-actions.outputs.should_skip }}
    steps:
      - id: check-permissions
        name: Check action permissions
        uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        if: env.CHECK_PERMISSIONS == '1'
      - id: check-duplicate-actions
        name: Check for duplicate actions
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          cancel_others: true
          skip_after_successful_duplicate: true
          concurrent_skipping: same_content_newer

  review-deps:
    name: Review Dependencies
    needs: pre_job
    if: github.actor != 'dependabot[bot]' && needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: write # Updates PR comments
    steps:
      - id: checkout-repo
        name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - id: review-deps
        name: Review dependencies
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          base-ref: main
          head-ref: main
          fail-on-severity: high
          comment-summary-in-pr: always
