name: 'Dependency Review'
on:
  push:

  pull_request_target:
    types: [opened, reopened]

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

  # https://www.meziantou.net/how-to-cancel-github-workflows-when-pushing-new-commits-on-a-branch.htm
concurrency:
  # pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre_job:
    name: Check for Duplicate Actions
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          skip_after_successful_duplicate: 'true'
          concurrent_skipping: same_content_newer

  dependency-review:
    name: Review Dependencies
    needs: pre_job
    if: github.actor != 'dependabot[bot]' && needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - id: checkout
        name: 'Checkout Repository'
        uses: actions/checkout@v5.0.0

      - id: review-deps
        name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          base-ref: main
          head-ref: main
          fail-on-severity: high
          comment-summary-in-pr: always
