on:
  pull_request:
    branches: [main]

  push:
    branches:
    - main

  schedule:
  - cron: '0 0 * * 0'

  workflow_dispatch:
    inputs:
      reason:
        description: "The reason for running the workflow"
        required: true
        default: "Manual run"

name: Semgrep

jobs:
  pre_job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          skip_after_successful_duplicate: 'true'
          concurrent_skipping: same_content_newer

  semgrep:
    name: Semgrep/CI
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
      # https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      options: --user 1001

    steps:
    - id: checkout
      name: 'Checkout Repository'
      uses: actions/checkout@v4.2.2

    - id: filter
      name: "Check for changed files"
      uses: dorny/paths-filter@v3
      with:
        filters: .github/filter.yml

    - id: run-semgrep
      name: 'Run Semgrep'
      if: steps.filter.outputs.code == 'true' || steps.filter.outputs.workflows == 'true'
      run: semgrep ci
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
