name: Update PR

on:
  push:
    branches:
      - 'main'
jobs:
  autoupdate:
    name: Update PR
    runs-on: ubuntu-latest
    steps:
      - id: update-pr
        name: Automatically update PR
        uses: adRise/update-pr-branch@v0.10.1
        with:
          # Add secret here: https://github.com/{owner}/{repo}/settings/secrets/actions
          token: ${{ secrets.ACTION_USER_TOKEN }}
          base: 'main'
          required_approval_count: 0
          require_passed_checks: true
          require_auto_merge_enabled: false
          allow_ongoing_checks: true
